# Manual page installation (section 8)
#
############################################################
#
# @(#) $Header: /xtel/pp/pp-beta/man/man8/RCS/Makefile,v 6.0 1991/12/18 20:44:03 jpo Rel $
#
# $Log: Makefile,v $
# Revision 6.0  1991/12/18  20:44:03  jpo
# Release 6.0
#
#
############################################################
#
# Definitions
#
############################################################



MANUALS	= MTAconsole.8 \
	abbrev.8 \
	ckadr.8 \
	ckchan.8 \
	ckconfig.8 \
	dbmbuild.8 \
	dbmedit.8 \
	dbmunbuild.8 \
	lconsole.8 \
	mpp84.8 \
	mpp88.8 \
	pp-gen.8 \
	pptsapd.8 \
	probe.8 \
	qmgr.8 \
	rmail.8 \
	sendmail.8 \
	smtpd.8 \
	smtpsrvr.8 \
	tjoin.8



############################################################
#
# Building Rules
#
############################################################

default:;

install:; MANDIR=$(MANDIR) ../inst-man.sh $(MANOPTS) $(MANUALS)

clean:;
tidy:;
lint:;
depend:;

############################################################
#
# End of Building Rules
#
############################################################
