.TH RMAIl 8
.\" @(#) $Header: /xtel/pp/pp-beta/man/man8/RCS/rmail.8,v 6.0 1991/12/18 20:44:03 jpo Rel $
.\"
.\" $Log: rmail.8,v $
.\" Revision 6.0  1991/12/18  20:44:03  jpo
.\" Release 6.0
.\"
.\"
.\"
.SH NAME
rmail \- handle remote mail received via uucp
.SH SYNOPSIS
.in +.5i
.ti -.5i
rmail 
\%[recipient...]
.in -.5i
.SH DESCRIPTION
\fIrmail\fP provides the gateway from uucp to the PP mail system.
It interprets incoming mail received via uucp and passes the
processed mail on to the \fIsubmit\fP process.
