# Manual page installation (section 1)
#
############################################################
#
# @(#) $Header: /xtel/pp/pp-beta/man/man1/RCS/Makefile,v 6.0 1991/12/18 20:43:41 jpo Rel $
#
# $Log: Makefile,v $
# Revision 6.0  1991/12/18  20:43:41  jpo
# Release 6.0
#
#
############################################################
#
# Definitions
#
############################################################



MANUALS	= ckmail.1 \
	ckmf.1 \
	dl.1 \
	flagmail.1 \
	flock.1 \
	mail.1 \
	malias.1 \
	mlist.1 \
	ntail.1 \
	rcvtrip.1 \
	resend.1 \
	strip_addr.1 \
	ttyalert.1 \
	ttybiff.1 \
	xalert.1


############################################################
#
# Building Rules
#
############################################################

default:;

install:; MANDIR=$(MANDIR) ../inst-man.sh $(MANOPTS) $(MANUALS)

clean:;
tidy:;
lint:;
depend:;

############################################################
#
# End of Building Rules
#
############################################################
