.TH MALIAS 1
.\" @(#) $Header: /xtel/pp/pp-beta/man/man1/RCS/malias.1,v 6.0 1991/12/18 20:43:41 jpo Rel $
.\"
.\" $Log: malias.1,v $
.\" Revision 6.0  1991/12/18  20:43:41  jpo
.\" Release 6.0
.\"
.\"
.\"
.SH NAME
malias \- distribution list viewer
.SH SYNOPSIS
.in +.5i
.ti -.5i
malias
\%[listname ...]
.in -.5i
.SH DESCRIPTION
The
.I malias
program is used to show the expansion of the lists specified on the
command line.
If no lists are specified, malias enters an interactive mode prompting
the user for lists to show.
.SH "SEE ALSO"
mlist(1)
.sp
\fIThe PP Manual: Volume 3 \- Users Guide\fP
