.TH MLIST 1
.\" @(#) $Header: /xtel/pp/pp-beta/man/man1/RCS/mlist.1,v 6.0 1991/12/18 20:43:41 jpo Rel $
.\"
.\" $Log: mlist.1,v $
.\" Revision 6.0  1991/12/18  20:43:41  jpo
.\" Release 6.0
.\"
.\"
.\"
.SH NAME
mlist \- distribution list manager
.SH SYNOPSIS
.in +.5i
.ti -.5i
mlist
\%[listname ...]
.br
malias
\%[listname ...]
.in -.5i
.SH DESCRIPTION
The
.I mlist
program is used to modify the lists specified on the command line.
If no lists are specified, mlist enters an
interactive mode prompting the user for lists to modify.
When modifying a list, \fImlist\fP allows the user to create, add,
remove, display, and check distribution lists via menu items.
.PP
The
.I malias
program is used to show the expansion of the lists specified on the
command line.
If no lists are specified, \fImalias\fP enters an interactive mode prompting
the user for lists to show.
.SH "SEE ALSO"
\fIThe PP Manual: Volume 3 \- Users Guide\fP
